const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "API de Gerenciamento de projetos",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['../../webservice/auth/routes']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('../../webservice/main')
})